In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('amazon_reviews_us_Grocery_v1_00.tsv.gz', 
                 nrows=40000, sep='\t', error_bad_lines=False)

b'Skipping line 1925: expected 15 fields, saw 22\nSkipping line 1977: expected 15 fields, saw 22\nSkipping line 35265: expected 15 fields, saw 22\n'


In [2]:
df.head(5)


marketplace  customer_id       review_id  product_id  product_parent  \
0          US     42521656  R26MV8D0KG6QI6  B000SAQCWC       159713740   
1          US     12049833  R1OF8GP57AQ1A0  B00509LVIQ       138680402   
2          US       107642  R3VDC1QB6MC4ZZ  B00KHXESLC       252021703   
3          US      6042304  R12FA3DCF8F9ER  B000F8JIIC       752728342   
4          US     18123821   RTWHVNV6X4CNJ  B004ZWR9RQ       552138758   

                                       product_title product_category  \
0  The Cravings Place Chocolate Chunk Cookie Mix,...          Grocery   
1            Mauna Loa Macadamias, 11 Ounce Packages          Grocery   
2  Organic Matcha Green Tea Powder - 100% Pure Ma...          Grocery   
3  15oz Raspberry Lyons Designer Dessert Syrup Sauce          Grocery   
4  Stride Spark Kinetic Fruit Sugar Free Gum, 14-...          Grocery   

   star_rating  helpful_votes  total_votes vine verified_purchase  \
0            5              0            0    N                 Y   
1            5              0            0    N                 Y   
2            5              0            0    N                 N   
3            5              0            0    N                 Y   
4            5              0            0    N                 Y   

                      review_headline  \
0  Using these for years - love them.   
1                           Wonderful   
2                          Five Stars   
3                          Five Stars   
4                          Five Stars   

                                         review_body review_date  
0  As a family allergic to wheat, dairy, eggs, nu...  2015-08-31  
1  My favorite nut.  Creamy, crunchy, salty, and ...  2015-08-31  
2  This green tea tastes so good! My girlfriend l...  2015-08-31  
3  I love Melissa's brand but this is a great sec...  2015-08-31  
4                                               good  2015-08-31

In [3]:
df = df.drop(['marketplace', 'product_category'], axis=1)

df = df[~df['review_body'].isnull()]

df['review_body'] = df['review_headline'] + '. ' + df['review_body']

In [4]:
df = df[df['review_body'].apply(len) > 40]

In [5]:
customer_count = df.groupby(['customer_id', 'review_date'])['product_id'].count().reset_index()
customer_count.columns = ['customer_id', 'review_date', 'review_count']

customer_count = customer_count[customer_count['review_count'] > 5]
customer_count.sort_values(by='review_count')

customer_id review_date  review_count
0            10805  2015-08-19             6
9985      20613913  2015-08-25             6
10787     22476158  2015-08-21             6
11026     22943881  2015-08-22             6
11169     23220887  2015-08-22             6
...            ...         ...           ...
16492     36290808  2015-08-31            15
16911     37293783  2015-08-19            17
1093       1535682  2015-08-28            17
10027     20674418  2015-08-29            18
8420      17162238  2015-08-24            29

[118 rows x 3 columns]

In [6]:
df[df['customer_id'] == 1535682]

customer_id       review_id  product_id  product_parent  \
8505       1535682  R259ZCCPVMAO4Z  B0082B7P16       533825475   
8552       1535682  R1U0ADA596INCW  B00KZNGP4W       910616800   
8592       1535682  R29862ZMJ5E277  B000YPQC08       706238482   
8604       1535682  R3AIOO6EDMJ2JC  B001IZ8AAI       785993145   
8962       1535682  R146UDOTGKUHCF  B001SAZJ6G       551061531   
9404       1535682  R3ECPWWZ4QOKTB  B005K4Q1YA       795563511   
9412       1535682  R3JUBQBB08SFIT  B00E9NZC66       389243328   
9513       1535682   RUQZR7KY5TQJD  B00FMBL5G0       452891721   
9729       1535682  R1IC88YG7VGYJI  B001FA1EVS       800370059   
9830       1535682  R2BG6L1ZHRV961  B00OGLTBXG       803158222   
9903       1535682  R3GZ5S0WPOCW2E  B005EKI7EW       329820159   
10041      1535682  R2SAV20RJIJ27D  B000R7RNWY       485934973   
10179      1535682  R1FB7E502YED8F  B003WEFQ3W       999635636   
10545      1535682    RMOQBF89R8BJ  B000EMQG5C       775181269   
10662      1535682  R22FM9C0Y8NKB9  B001EPPCFS       467913653   
10693      1535682  R3EQVQV9HKVYYX  B00CJC93MI       318090365   
10712      1535682  R13YESNI6BJSAD  B00IO2LDCA       385136451   

                                           product_title  star_rating  \
8505            Hollywood Safflower Oil, 32 Ounce Bottle            5   
8552                             Campbell's Pork & Beans            5   
8592   Rice-A-Roni Herb & Butter, 7.2-Ounce Boxes (Pa...            5   
8604     Freedent Gum, 15-Stick Plen-T-Paks (Pack of 24)            5   
8962               Krusteaz Fat Free Honey Cornbread Mix            4   
9404   Grove Square Cappuccino, Single Serve Cup for ...            5   
9412   Campbell's Chunky Soup, Variety Pack, 18.6 Oun...            5   
9513                        Gevalia Cafe Style Beverages            5   
9729                Hershey's Special Dark Chocolate Bar            5   
9830                 BIALY, BY THE DOZEN [ TWO 6 PACKS ]            5   
9903   Old El Paso Hard and Soft Dinner Kit Twin Pack...            5   
10041  Ruffles Ridged Potato Chips, Cheddar Sour Crea...            5   
10179                                Breath Savers Mints            5   
10545  Betty Crocker Cake & Cookie Mix Gingerbread 14...            5   
10662                                 McVitie's Biscuits            4   
10693  Andrew and Everett Grated Parmesan Cheese, 7 O...            5   
10712    Oreo Cookies Variety Pack, 12 Count (Pack of 4)            5   

       helpful_votes  total_votes vine verified_purchase  \
8505               0            0    N                 Y   
8552               0            1    N                 Y   
8592               0            0    N                 Y   
8604               0            0    N                 Y   
8962               0            0    N                 Y   
9404               0            0    N                 Y   
9412               0            1    N                 Y   
9513               0            0    N                 Y   
9729               0            0    N                 Y   
9830               0            0    N                 Y   
9903               0            0    N                 Y   
10041              0            0    N                 Y   
10179              0            0    N                 Y   
10545              0            0    N                 Y   
10662              1            1    N                 Y   
10693              0            0    N                 N   
10712              0            0    N                 N   

                                         review_headline  \
8505                                          Five Stars   
8552                                          Five Stars   
8592                                          Five Stars   
8604                                          Five Stars   
8962               Very moist Great product Easy to make   
9404                     I enjoyed these Flavor was good   
94

In [7]:
df['review_body'].value_counts()

Best brand spice blends out there!!. Teeny Tiny Spice Co. RULES!!!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

In [8]:
df[df['review_body'] == 'Best brand spice blends out there!!. Teeny Tiny Spice Co. RULES!!!']

customer_id       review_id  product_id  product_parent  \
5722     20674418  R2B0RX6RUFGRCT  B007NZTMSQ       663121827   
6080     20674418  R23PPHOR6LS9CF  B0063J1PLU       802153228   
6110     20674418  R26AW9IZTR2HJJ  B0063J1QFK       227819371   
6298     20674418   RUC1TPP14YR6P  B0063J1KLK       945713958   
6329     20674418  R1897JIK6NN4G6  B00CC397L6       740716851   
6342     20674418  R28D3ENJ06TYTQ  B007NZUK6O        81301745   
6380     20674418  R2XWQKNCNUZZYR  B0063J1QAA       377745278   
6385     20674418  R197MAUPKSABDW  B0063J1P9W       654564533   
6395     20674418   R74UT22PYF3N4  B00LG03GYA       461204413   
6691     20674418  R2JRXLS0WY6DA1  B0063J1QTG        99517704   
6812     20674418  R36QVC7GOWT8TD  B00CC2RLJC       535849634   
7109     20674418  R33XFE34AR4VFN  B00CC3487E       537243903   
7413     20674418   RHUT1PT0STUGR  B0063J1OW0       102523625   
7508     20674418  R3FKL0HM9ZXZJR  B0063J1RCM       875622473   
7534     20674418  R1T4GEFLYGLU1E  B00CC31AV6        15665018   
7823     20674418  R12ZYHFJSX4QSQ  B0063J1KFQ       372015296   
8341     20674418   RPY74EOSIA46V  B007O0222S       624854368   

                                          product_title  star_rating  \
5722  Teeny Tiny Spice Co of Vermont Kosher Himalaya...            5   
6080  Teeny Tiny Spice Co of Vermont Organic Persian...            5   
6110  Teeny Tiny Spice Co. of Vermont Organic Tandoo...            5   
6298  Teeny Tiny Spice Co. of Vermont Organic Britis...            5   
6329  Teeny Tiny Spice Co. of Vermont Organic WhoopA...            5   
6342  Teeny Tiny Spice Co of Vermont Organic Harissa...            5   
6380  Teeny Tiny Spice Co. of Vermont Organic Shephe...            5   
6385  Teeny Tiny Spice Co. of Vermont Organic Perfec...            5   
6395  Teeny Tiny Spice Company Organic Hot Italian S...            5   
6691  Teeny Tiny Spice Co. of Vermont Organic Vadava...            5   
6812  Teeny Tiny Spice Co. of Vermont Organic Oaxaca...            5   
7109  Teeny Tiny Spice Co. of Vermont Organic Szechu...            5   
7413  Teeny Tiny Spice Co of Vermont Organic Montréa...            5   
7508  Teeny Tiny Spice Co. of Vermont Organic Za'ata...            5   
7534  Teeny Tiny Spice Co. of Vermont Organic Toluca...            5   
7823  Teeny Tiny Spice Co of Vermont Organic Afghani...            5   
8341  Teeny Tiny Spice Co of Vermont Organic Jamaica...            5   

      helpful_votes  total_votes vine verified_purchase  \
5722              1            1    N                 Y   
6080              1            1    N                 Y   
6110              1            1    N                 Y   
6298              1            1    N                 Y   
6329              1            1    N                 Y   
6342              1            1    N                 Y   
6380              0            0    N                 Y   
6385              1            2    N                 Y   
6395              2            2    N                 Y   
6691              1            2    N                 Y   
6812              1            2    N                 Y   
7109              2            2    N                 Y   
7413              1            1    N                 Y   
7508              1            1    N                 Y   
7534              0            0    N                 Y   
7823              1            1    N                 Y   
8341              1            1    N                 Y   

                          review_headline  \
5722  Best brand spice blends out there!!   
6080  Best brand spice blends out there!!   
6110  Best brand spice blends out there!!   
6298  Best brand spice blends out there!!   
6329  Best brand spice blends out there!!   
6342  Best brand spice blends out there!!   
6380  Best brand spice blends out there!!   
6385  Best brand spice blends out there!!   
6395  Best brand spice blends out there!!   
6691  Best brand spice bl

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=5000)
review_tfidf = tfidf.fit_transform(df['review_body'])

In [10]:
review_tfidf.shape

(30975, 5000)

In [11]:
IDX = 0

bad_list = []


for IDX_start in range(int(review_tfidf.shape[0]/1000) +1):
    idss = np.dot(
        review_tfidf[
            IDX_start*1000:
            (IDX_start+1)*1000
        ], 
        review_tfidf.T
    ).toarray()
    # 0， 1
    
    for ids in idss:
        IDX += 1
        if len(np.where(ids >= 0.99)[0])==1:
            continue
        

        print(np.where(ids >= 0.99)[0])
        
        bad_list.extend(list(np.where(ids >= 0.99)[0]))
        # A -> B
        # B -> A

[   57   226   813   925  1180  1198  1877  2334 24579]
[  74  208  251  655 1328 1381 1636 1846 1856 1976 1980]
[  139 10017 12308 12408 12457 12893]
[ 188  515 1089 1292 2179]
[  74  208  251  655 1328 1381 1636 1846 1856 1976 1980]
[   57   226   813   925  1180  1198  1877  2334 24579]
[  74  208  251  655 1328 1381 1636 1846 1856 1976 1980]
[ 260  405  872 1889 2058]
[288 649 926]
[ 260  405  872 1889 2058]
[ 188  515 1089 1292 2179]
[ 533 1793]
[288 649 926]
[  74  208  251  655 1328 1381 1636 1846 1856 1976 1980]
[ 668 1475]
[760 861]
[ 812 1705]
[   57   226   813   925  1180  1198  1877  2334 24579]
[  857 24615]
[760 861]
[ 260  405  872 1889 2058]
[   57   226   813   925  1180  1198  1877  2334 24579]
[288 649 926]
[ 958 1558]
[ 188  515 1089 1292 2179]
[   57   226   813   925  1180  1198  1877  2334 24579]
[   57   226   813   925  1180  1198  1877  2334 24579]
[1239 1887]
[1260 2125]
[ 188  515 1089 1292 2179]
[  74  208  251  655 1328 1381 1636 1846 1856 1976 1980]
[  7

[15960 16306 17017 17248]
[16620 17021]
[15517 15728 16147 16446 16461 16474 16605 16755 16930 17054 17163 17164
 17675 17763]
[15364 15819 17096 17566 17804]
[15640 16813 16967 17137 17797 25550 29483]
[15517 15728 16147 16446 16461 16474 16605 16755 16930 17054 17163 17164
 17675 17763]
[15517 15728 16147 16446 16461 16474 16605 16755 16930 17054 17163 17164
 17675 17763]
[16123 17169]
[16352 17178]
[15960 16306 17017 17248]
[17289 29269]
[17290 17307]
[15511 15513 15575 17302]
[17290 17307]
[15385 17461]
[15807 15862 16194 16838 16879 17480 17547 17637]
[15791 16262 16524 16811 17501]
[17534 17660]
[15807 15862 16194 16838 16879 17480 17547 17637]
[15364 15819 17096 17566 17804]
[15807 15862 16194 16838 16879 17480 17547 17637]
[17534 17660]
[15517 15728 16147 16446 16461 16474 16605 16755 16930 17054 17163 17164
 17675 17763]
[15411 17710]
[15517 15728 16147 16446 16461 16474 16605 16755 16930 17054 17163 17164
 17675 17763]
[15640 16813 16967 17137 17797 25550 29483]
[15364 15819 

In [12]:
df.iloc[[ 188,515,1089,1292,2179]]

customer_id       review_id  product_id  product_parent  \
248      46879740  R2TFOK34TFLF8Z  B000E1FZJG       715147429   
655      46879740   RUUVVVMHNB4RQ  B001EQ4LFO       303493570   
1397     46879740   RARVQBJ9PXR8P  B0002EW9AI       457220290   
1659     46879740  R3SVYCOXEXCYDV  B000E1HW3S       731475090   
2825     46879740  R3H9HT7ZG3YZW4  B0002EVTEK       561831874   

                                          product_title  star_rating  \
248   Taco Bell Taco Seasoning, 1-Ounce Pouches (Pac...            5   
655   Aspen Cider Spices, Original Spice Blend, 5.65...            5   
1397  Aspen Mulling Cider Spice 3 Pack - Original Sp...            5   
1659  Taco Bell Home Originals Fajita Seasoning Mix,...            5   
2825  Aspen Mullings Original Spice Blend - Cider Sp...            5   

      helpful_votes  total_votes vine verified_purchase review_headline  \
248               0            0    N                 Y      Five Stars   
655               0            0    N                 Y      Five Stars   
1397              0            0    N                 Y      Five Stars   
1659              0            0    N                 Y      Five Stars   
2825              0            0    N                 Y      Five Stars   

                                            review_body review_date  
248   Five Stars. Is exactly what I wanted.  Will bu...  2015-08-31  
655   Five Stars. Is exactly what I wanted.  Will bu...  2015-08-31  
1397  Five Stars. Is exactly what I wanted.  Will bu...  2015-08-31  
1659  Five Stars. Is exactly what I wanted.  Will bu...  2015-08-31  
2825  Five Stars. Is exactly what I wanted.  Will bu...  2015-08-31

In [13]:
df.iloc[list(set(bad_list))]

customer_id       review_id  product_id  product_parent  \
31647     53028949  R2FUX3Y5UIUF9Y  B00BG0ZJ0Y       338444197   
18437     17162238   RSF3A26NX9DQA  B00LBYM5GQ       115297401   
2676      41137196  R3CLAEW5DO5WMO  B00T17KM7O       648661984   
26387     36891841  R2N3RRAGN7Y24V  B005FC730S       601212660   
15847     33589781  R286YUZH9AZGPL  B00H6Z4J6I       799657202   
...            ...             ...         ...             ...   
7998      48509688  R1KBQWN53PWSU1  B00HKWQ1XQ       847505009   
28956     42172385  R330N5PIANOEH4  B0038M5TL2       164135236   
15794     40110175  R1VKNLJ928GPYO  B002YAYZR8       406196980   
5328      33999035  R28HDZ7UVGHN9D  B002YR7A9Q       308684583   
23705     43488499  R16GWXRBWOA1CA  B000E65OK6       569161904   

                                           product_title  star_rating  \
31647      Matcha DNA Certified Organic Matcha Green Tea            5   
18437                               Happy Me Tea, NEW!!!            2   
2676   The Gourmet Collection, Oregano, Basil& Tomato...            5   
26387  Oat Bars Gluten Free Lemon Poppyseed, 3 oz(Pac...            5   
15847  Annie's Homegrowns Variety Macaroni and Cheese...            5   
...                                                  ...          ...   
7998   Cadbury Drinking Chocolate 225g (Made in Austr...            5   
28956             Sparkling Water Essence Currant Flavor            5   
15794                Sugar-Free All Natural Sour Candies            5   
5328   Bob's Red Mill Shredded Coconut Unsweetened, 1...            4   
23705                           Celestial Seasonings Tea            5   

       helpful_votes  total_votes vine verified_purchase  \
31647              0            0    N                 Y   
18437              1            2    N                 N   
2676               0            0    N                 Y   
26387              0            0    N                 Y   
15847              0            0    N                 Y   
...              ...          ...  ...               ...   
7998               1            1    N                 Y   
28956              0            0    N                 Y   
15794              0            0    N                 Y   
5328               0            0    N                 Y   
23705              0            0    N                 Y   

                                         review_headline  \
31647                                         Five Stars   
18437  has no taste at all, but made with organic ing...   
2676                                          Five Stars   
26387               Love these oat bars - they are tasty   
15847                                     great product.   
...                                                  ...   
7998                                          Five Stars   
28956                 tastes good. No syrupy after taste   
15794                                         Five Stars   
5328                      As advertised and no surprises   
23705             Great herbal tea at a very good price.   

                                             review_body review_date  
31647       Five Stars. Arrived on time - great product!  2015-08-20  
18437  has no taste at all, but made with organic ing...  2015-08-25  
2676         Five Stars. I was pleased with the product.  2015-08-31  
26387  Love these oat bars - they are tasty. Love the...  2015-08-22  
15847      great product.. Fast shipping, great product.  2015-08-26  
...                                                  ...         ...  
7998     Five Stars. Item as described -- fast delivery.  2015-08-29  
28956  tastes good. No syrupy after taste. Natural fl...  2015-08-21  
15794       Five Stars. Arrived on time and as expected.  2015-08-26  
5328   As advertised and no surprises. As advertised ...  2015-08-30  
23705  Great herbal tea at a very good price.. Great ...  2015-08-23  

[586 rows x 13 columns]